### ISSUE TITLE
Improve load times of the TZP viewer

### ISSUE THREAD

**Issue by wyc** [spruceid/tzprofiles#91] opened 2021-05-27 22:59 UTC
As a User, I want to be able to see a profile within 250 ms of second page load, preferably upon the first page load as well.

Currently, some profiles take several seconds to load, which could be improved with a cache. This is due to the decentralized nature of the dApp and several calls to the BCD indexer and Kepler. Because the tzprofiles.com domain is already being trusted by the user, could we use our own API and cache the results for much better and consistent performance?

For example, [this profile](https://tzprofiles.com/view/tz1LMChSoDrZK8fFYmewVYnYe7q6tn43zFQs) takes 8 seconds to load completely:

<img width="1151" alt="Screen Shot 2021-05-27 at 8 10 54 PM" src="https://user-images.githubusercontent.com/858687/119911633-a6eb4b80-bf27-11eb-801f-60fe497594be.png">

**Comment by sbihel** [comment] 2021-06-16 12:21
Duplicate of #97 and closed in #96.

**Closed by sbihel** 2021-06-16 12:21 UTC
Labels: enhancement
